spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: trace