spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging.level:
  org.hibernate.SQL: trace