spring:
  profiles:
    include: oauth,real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always