spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
