spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging.level:
  org.hibernate.SQL: trace