spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

logging.level:
  org.hibernate.SQL: trace